spring.application.name=inter-mobi

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/inter_mobi
spring.datasource.username=inter_mobi_user
spring.datasource.password=inter_mobi_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
